// Default routine. `minutes` = minutes after midnight (used for ordering and
// "missed" detection). `label` overrides the clock time for flexible slots.
export const DEFAULT_TASKS = [
  {
    id: 'fajr',
    minutes: 330,
    label: '',
    category: 'Faith',
    name: 'Fajr Prayer + Quran',
    description: 'Start the day with Allah, Quran, and reflection.',
    rule: '',
  },
  {
    id: 'messages',
    minutes: 390,
    label: '',
    category: 'Communication',
    name: 'Check messages and emails',
    description: 'Only important communication.',
    rule: 'Avoid social media.',
  },
  {
    id: 'morning-move',
    minutes: 420,
    label: '',
    category: 'Health',
    name: 'Cycling + Walking + Fresh Air + Shower',
    description: 'Move the body and reset the mind.',
    rule: '',
  },
  {
    id: 'plan',
    minutes: 480,
    label: '',
    category: 'Planning',
    name: "Plan today's priorities",
    description: 'Decide what matters most before the day decides for you.',
    rule: '',
  },
  {
    id: 'deep-work-1',
    minutes: 510,
    label: '',
    category: 'Work',
    name: 'Deep Work Session',
    description: 'Business, design, and technology progress.',
    rule: 'One task at a time. No multitasking.',
  },
  {
    id: 'lunch',
    minutes: 780,
    label: '',
    category: 'Break',
    name: 'Lunch Break',
    description: 'Eat slowly and rest the mind.',
    rule: 'Read books while eating.',
  },
  {
    id: 'deep-work-2',
    minutes: 840,
    label: 'After Lunch',
    category: 'Work',
    name: 'Second Deep Work Session',
    description: 'Continue the most important work of the day.',
    rule: 'One task at a time. No multitasking.',
  },
  {
    id: 'afternoon-move',
    minutes: 1020,
    label: 'Afternoon',
    category: 'Health',
    name: 'Walking + Cycling',
    description: 'Get outside and keep the body moving.',
    rule: '',
  },
  {
    id: 'relax',
    minutes: 1140,
    label: 'Evening',
    category: 'Relaxation',
    name: 'Movie / Series Time',
    description: 'Rest intentionally. Recovery is part of discipline.',
    rule: '',
  },
  {
    id: 'learning',
    minutes: 1260,
    label: 'After 9 PM',
    category: 'Learning',
    name: 'Explore new knowledge',
    description: 'Books, research, virtual meetings.',
    rule: '',
  },
  {
    id: 'islamic-book',
    minutes: 1350,
    label: 'Before Sleep',
    category: 'Faith',
    name: 'Read Islamic Book',
    description: 'End the day with knowledge that nourishes the soul.',
    rule: '',
  },
  {
    id: 'sleep',
    minutes: 1380,
    label: 'Sleep Routine',
    category: 'Life',
    name: 'No phone before and after sleep',
    description: 'Protect your rest and your first moments of the day.',
    rule: '',
  },
];
